const data = [
  {
    id: 1,
    trackingId: "#20462",
    product: {
      name: "Hat",
      img: "./assets/hat.jpeg",
    },
    customer: "Matt Dickerson",
    date: "13/05/2022",
    ammount: "$4.95",
    paymentMode: "Tranfer Bank",
    status: "Delivered",
  },
  {
    id: 2,
    trackingId: "#18933",
    product: {
      name: "Laptop",
      img: "./assets/laptop.jpeg",
    },
    customer: "Wiktoria",
    date: "22/05/2022",
    ammount: "$8.95",
    paymentMode: "Cash on Delivery",
    status: "Delivered",
  },
  {
    id: 3,
    trackingId: "#45169",
    product: {
      name: "Phone",
      img: "./assets/phone.jpeg",
    },
    customer: "Trixie Byrd",
    date: "15/06/2022",
    ammount: "$1,149.95",
    paymentMode: "Cash on Delivery",
    status: "Process",
  },
  {
    id: 4,
    trackingId: "#34304",
    product: {
      name: "Bag",
      img: "./assets/bag.jpeg",
    },
    customer: "Brad Mason",
    date: "06/09/2022",
    ammount: "$899.95",
    paymentMode: "Tranfer Bank",
    status: "Process",
  },
  {
    id: 5,
    trackingId: "#17188",
    product: {
      name: "Headset",
      img: "./assets/headset.jpeg",
    },
    customer: "Sanderson",
    date: "25/09/2022",
    ammount: "$22.95",
    paymentMode: "Cash on Delivery",
    status: "Canceled",
  },
  {
    id: 6,
    trackingId: "#73003",
    product: {
      name: "Mouse",
      img: "./assets/mouse.jpeg",
    },
    customer: "Jun Redfern",
    date: "04/10/2022",
    ammount: "$54.95",
    paymentMode: "Tranfer Bank",
    status: "Delivered",
  },
  {
    id: 7,
    trackingId: "#58825",
    product: {
      name: "Clock",
      img: "./assets/clock.jpeg",
    },
    customer: "Miriam Kidd",
    date: "17/10/2022",
    ammount: "$174.95",
    paymentMode: "Tranfer Bank",
    status: "Delivered",
  },
  {
    id: 8,
    trackingId: "#44122",
    product: {
      name: "T-shirt",
      img: "./assets/tshirt.jpeg",
    },
    customer: "Dominic",
    date: "24/10/2022",
    ammount: "$249.95",
    paymentMode: "Cash on Delivery",
    status: "Delivered",
  },
  {
    id: 9,
    trackingId: "#89094",
    product: {
      name: "Monitor",
      img: "./assets/monitor.jpeg",
    },
    customer: "Shanice",
    date: "01/11/2022",
    ammount: "$899.95",
    paymentMode: "Tranfer Bank",
    status: "Canceled",
  },
  {
    id: 10,
    trackingId: "#85252",
    product: {
      name: "Keyboard",
      img: "./assets/keyboard.jpeg",
    },
    customer: "Poppy-Rose",
    date: "22/11/2022",
    ammount: "$6.948",
    paymentMode: "Tranfer Bank",
    status: "Process",
  },
  {
    id: 11,
    trackingId: "#98765",
    product: {
      name: "Hat",
      img: "./assets/hat.jpeg",
    },
    customer: "Miranda Lawson",
    date: "03/12/2022",
    ammount: "$4.95",
    paymentMode: "Transfer Bank",
    status: "Process",
  },
  {
    id: 12,
    trackingId: "#23456",
    product: {
      name: "Phone",
      img: "./assets/phone.jpeg",
    },
    customer: "Garrus Vakarian",
    date: "17/12/2022",
    ammount: "$1,149.95",
    paymentMode: "Cash on Delivery",
    status: "Canceled",
  },
  {
    id: 13,
    trackingId: "#54321",
    product: {
      name: "Laptop",
      img: "./assets/laptop.jpeg",
    },
    customer: "Tali'Zorah nar Rayya",
    date: "24/12/2022",
    ammount: "$8.95",
    paymentMode: "Tranfer Bank",
    status: "Process",
  },
  {
    id: 14,
    trackingId: "#87654",
    product: {
      name: "Bag",
      img: "./assets/bag.jpeg",
    },
    customer: "Jeff  Moreau",
    date: "05/01/2023",
    ammount: "$899.95",
    paymentMode: "Tranfer Bank",
    status: "Process",
  },
  {
    id: 15,
    trackingId: "#67890",
    product: {
      name: "Keyboard",
      img: "./assets/keyboard.jpeg",
    },
    customer: "EDI",
    date: "14/01/2023",
    ammount: "$6.948",
    paymentMode: "Tranfer Bank",
    status: "Delivered",
  },
  {
    id: 16,
    trackingId: "#54321",
    product: {
      name: "Laptop",
      img: "./assets/laptop.jpeg",
    },
    customer: "Liara T'Soni",
    date: "28/01/2023",
    ammount: "$8.95",
    paymentMode: "Cash on Delivery",
    status: "Delivered",
  },
  {
    id: 17,
    trackingId: "#98765",
    product: {
      name: "Hat",
      img: "./assets/hat.jpeg",
    },
    customer: "Jacob Taylor",
    date: "10/02/2023",
    ammount: "$4.95",
    paymentMode: "Transfer Bank",
    status: "Canceled",
  },
  {
    id: 18,
    trackingId: "#23456",
    product: {
      name: "Phone",
      img: "./assets/phone.jpeg",
    },
    customer: "Jack",
    date: "22/02/2023",
    ammount: "$1,149.95",
    paymentMode: "Cash on Delivery",
    status: "Process",
  },
  {
    id: 19,
    trackingId: "#87654",
    product: {
      name: "Bag",
      img: "./assets/bag.jpeg",
    },
    customer: "Thane Krios",
    date: "07/03/2023",
    ammount: "$899.95",
    paymentMode: "Transfer Bank",
    status: "Canceled",
  },
  {
    id: 20,
    trackingId: "#67890",
    product: {
      name: "Keyboard",
      img: "./assets/keyboard.jpeg",
    },
    customer: "Mordin Solus",
    date: "18/03/2023",
    ammount: "$6.948",
    paymentMode: "Transfer Bank",
    status: "Process",
  },
  {
    id: 21,
    trackingId: "#54321",
    product: {
      name: "Laptop",
      img: "./assets/laptop.jpeg",
    },
    customer: "Legion",
    date: "27/03/2023",
    ammount: "$8.95",
    paymentMode: "Cash on Delivery",
    status: "Process",
  },
  {
    id: 22,
    trackingId: "#98765",
    product: {
      name: "Hat",
      img: "./assets/hat.jpeg",
    },
    customer: "Samara",
    date: "09/04/2023",
    ammount: "$4.95",
    paymentMode: "Transfer Bank",
    status: "Delivered",
  },
  {
    id: 23,
    trackingId: "#23456",
    product: {
      name: "Phone",
      img: "./assets/phone.jpeg",
    },
    customer: "Grunt",
    date: "16/04/2023",
    ammount: "$1,149.95",
    paymentMode: "Cash on Delivery",
    status: "Canceled",
  },
];

export default data;
